#! /usr/bin/python3

# This app uses the pyChicken Python module to run a small social media
# platform on a Raspberry Pi with a PIR motion detector and infrared camera

from optparse import OptionParser
import os
import sys
from pychicken import pyChicken

def main():
  parser = OptionParser()
  parser.add_option("-c", "--config", dest="config",
                    help="Config file. Default is .pychicken.conf", metavar="CONFIG_FILE")

  (options, args) = parser.parse_args()

  pychicken = pyChicken(options)
  pychicken.run()

if __name__ == '__main__':
    main()